// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jamkbccmlgwsjpnndcce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphbWtiY2NtbGd3c2pwbm5kY2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDA1NjUsImV4cCI6MjA2MDQ3NjU2NX0.pS4BsHnN950cXb63Ww60gxRGjbcd9Y2X6YFhohKjdkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);